analyzers = [
  "pynsy.analyses.shape_inference"
]

[instrumentation_rules]
include = [
  "pynsy.demos",
]
exclude = [
  "jax",
  "optax",
  "pynsy",
  "pynsy.demos.haiku.examples.transformer.dataset",
]
