analyzers = [
  "pynsy.type_inference.tensor_shape_inference"
]

[instrumentation_rules]
include = [
  "pynsy.demos",
  # "levanter",
  "levanter.main",
  "levanter.models",
  # "tensorflow_models",
  "official.nlp.modeling.models",
  "official.nlp.modeling.networks",
  "tf_mnist",
]
exclude = [
  "jax",
  "optax",
  "pynsy",
  "pynsy.demos.haiku.examples.transformer.dataset",
  "tensorflow",
  "keras",
]
